### ISSUE TITLE
Uncaught TypeError: this._debug is not a function

### ISSUE THREAD

**Issue by schlamar** [sadovnychyi/autocomplete-python#105]
I just modified some Python code.

**Atom Version**: 1.1.0
**System**: KE-N06
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.9.3

### Stack Trace

Uncaught TypeError: this._debug is not a function

```
At /C:/Users/schlaich/.atom/packages/autocomplete-python/lib/provider.coffee:79

TypeError: this._debug is not a function
  at provider.BufferedProcess.stderr (C:\Users\schlaich\.atom\packages\autocomplete-python\lib\provider.coffee:66:10)
  at Socket.<anonymous> (C:\Users\schlaich\AppData\Local\atom\app-1.1.0\resources\app.asar\src\buffered-process.js:85:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:520:20)

```

### Commands

```
     -1:33 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:32.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:28.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:25.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:25.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:25.7.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:24.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:24.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:18.6.0 editor:newline (atom-text-editor.editor.is-focused)
  7x -1:15 core:backspace (atom-text-editor.editor.is-focused)
     -1:03.8.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -1:02.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:50.1.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:46.3.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:39 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:37.4.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".tox",
      ".cache",
      "*.pyc",
      "*.egg-info",
      "dist"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.16
autocomplete-python, v0.9.3
keyboard-localization, v1.4.10
language-cython, v0.3.0
linter, v1.9.1
linter-flake8, v1.9.1
minimap, v4.15.0
monokai, v0.18.0
python-tools, v0.6.5

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
Thanks for report -- fixed!
https://github.com/sadovnychyi/autocomplete-python/commit/dd459123e8afa3262d3524fc284ea4472ba48c63

**Comment by schlamar** [comment]
Wow, this was fast :cake:
