### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by schlamar** [sadovnychyi/autocomplete-python#109]
Could be an upstream (jedi) bug. Or you are sending invalid data:

    Traceback (most recent call last):
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib/completion.py", line 250, in watch
        self._process_request(self._input.readline())
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib/completion.py", line 241, in _process_request
        self._serialize_completions(script, request['id']))
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib/completion.py", line 79, in _serialize_completions
        call_signatures = script.call_signatures()
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\api\__init__.py", line 525, in call_signatures
        self.source, self._pos)
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\cache.py", line 93, in wrapper
        value = next(generator)
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\cache.py", line 115, in cache_call_signatures
        yield evaluator.eval_element(call)
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\evaluate\cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\evaluate\__init__.py", line 187, in eval_element
        types = self.eval_trailer(types, trailer)
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\evaluate\__init__.py", line 257, in eval_trailer
        new_types += self.find_types(typ, node)
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\evaluate\__init__.py", line 117, in find_types
        scopes = f.scopes(search_global)
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\evaluate\finder.py", line 109, in scopes
        return ((n, None) for n in self.scope.names_dicts(search_global))
    AttributeError: 'NoneType' object has no attribute 'names_dicts'

    Traceback (most recent call last):
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib/completion.py", line 250, in watch
        self._process_request(self._input.readline())
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib/completion.py", line 241, in _process_request
        self._serialize_completions(script, request['id']))
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib/completion.py", line 79, in _serialize_completions
        call_signatures = script.call_signatures()
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\api\__init__.py", line 525, in call_signatures
        self.source, self._pos)
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\cache.py", line 93, in wrapper
        value = next(generator)
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\cache.py", line 115, in cache_call_signatures
        yield evaluator.eval_element(call)
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\evaluate\cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\evaluate\__init__.py", line 187, in eval_element
        types = self.eval_trailer(types, trailer)
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\evaluate\__init__.py", line 257, in eval_trailer
        new_types += self.find_types(typ, node)
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\evaluate\__init__.py", line 117, in find_types
        scopes = f.scopes(search_global)
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib\jedi\evaluate\finder.py", line 109, in scopes
        return ((n, None) for n in self.scope.names_dicts(search_global))
    AttributeError: 'NoneType' object has no attribute 'names_dicts'

    Traceback (most recent call last):
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib/completion.py", line 250, in watch
        self._process_request(self._input.readline())
      File "C:\Users\schlaich\.atom\packages\autocomplete-python\lib/completion.py", line 241, in _process_request
        self._serialize_completions(script, request['id']))

**Comment by sadovnychyi** [comment]
Yeah, this is Jedi bug. And you shouldn't be seeing this unless you have Output provider errors setting set to true.
