### ISSUE TITLE
Autocomplete stops after any minutes on Linux

### ISSUE THREAD

**Issue by FTCr** [sadovnychyi/autocomplete-python#112]
What information I must give?

**Comment by sadovnychyi** [comment]
What do you mean "stops"? Stop working? But before it works? Can you enable debug in package setting and show me some logs from dev console?

**Comment by FTCr** [comment]
> Stop working? But before it works?

Yes :-(
> show me some logs from dev console

https://gist.github.com/FTCr/53f516a112479785fb75

**Comment by sadovnychyi** [comment]
It seems like everything is good. Anything in console when it actually stop working? Can you also set Output provider errors to True in settings?

**Comment by FTCr** [comment]
> Anything in console when it actually stop working?

I did not see.

> Can you also set Output provider errors to True in settings?

![2015-11-04-191859_748x181_scrot](https://cloud.githubusercontent.com/assets/3773642/10944206/131e07f2-8329-11e5-92de-3dbe515038f1.png)

**Comment by sadovnychyi** [comment]
Does other providers work for you when autocomplete python doesn't?

**Comment by FTCr** [comment]
Yes. Other providers work well.
Tested on other file.

**Comment by sadovnychyi** [comment]
Still cannot debug this issue. Need more information. Maybe you could put more debug statements into provider.coffee and look into the logs. Otherwise I cannot help you.

**Comment by FTCr** [comment]
WOW. :-( Good luck!

**Comment by FTCr** [comment]
I got the error today. May be it help.
```Traceback (most recent call last):
  File "/home/fil/.atom/packages/autocomplete-python/lib/completion.py", line 257, in watch
    self._process_request(self._input.readline())
  File "/home/fil/.atom/packages/autocomplete-python/lib/completion.py", line 248, in _process_request
    request.get('prefix', '')))
  File "/home/fil/.atom/packages/autocomplete-python/lib/completion.py", line 85, in _serialize_completions
    for pos, param in enumerate(call_signature.params):
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'
Traceback (most recent call last):
  File "/home/fil/.atom/packages/autocomplete-python/lib/completion.py", line 257, in watch
    self._process_request(self._input.readline())
  File "/home/fil/.atom/packages/autocomplete-python/lib/completion.py", line 248, in _process_request
    request.get('prefix', '')))
  File "/home/fil/.atom/packages/autocomplete-python/lib/completion.py", line 85, in _serialize_completions
    for pos, param in enumerate(call_signature.params):
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'
Traceback (most recent call last):
  File "/home/fil/.atom/packages/autocomplete-python/lib/completion.py", line 257, in watch
    self._process_request(self._input.readline())
  File "/home/fil/.atom/packages/autocomplete-python/lib/completion.py", line 248, in _process_request
    request.get('prefix', '')))
  File "/home/fil/.atom/packages/autocomplete-python/lib/completion.py", line 85, in _serialize_completions
    for pos, param in enumerate(call_signature.params):
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'
Traceback (most recent call last):
  File "/home/fil/.atom/packages/autocomplete-python/lib/completion.py", line 257, in watch
    self._process_request(self._input.readline())
  File "/home/fil/.atom/packages/autocomplete-python/lib/completion.py", line 248, in _process_request
    request.get('prefix', '')))
  File "/home/fil/.atom/packages/autocomplete-python/lib/completion.py", line 85, in _serialize_completions
    for pos, param in enumerate(call_signature.params):
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'
Traceback (most recent call last):
  File "/home/fil/.atom/packages/autocomplete-python/lib/completion.py", line 257, in watch
    self._process_request(self._input.readline())
  File "/home/fil/.atom/packages/autocomplete-python/lib/completion.py", line 248, in _process_request
    request.get('prefix', '')))
  File "/home/fil/.atom/packages/autocomplete-python/lib/completion.py", line 85, in _serialize_completions
    for pos, param in enumerate(call_signature.params):
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 352, in params
    return [_Param(self._evaluator, p.name) for p in params]
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 352, in <listcomp>
    return [_Param(self._evaluator, p.name) for p in params]
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 58, in __call__
    return super(CachedMetaClass, self).__call__(*args, **kwargs)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 508, in __init__
    super(Definition, self).__init__(evaluator, definition)
  File "/home/fil/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 64, in __init__
    self._definition = evaluator.wrap(self._name.get_definition())
AttributeError: 'Operator' object has no attribute 'get_definition'```

**Comment by sadovnychyi** [comment]
Can you reproduce this on specific code snippet or its just happens
randomly?

**Comment by vasa-chi** [comment]
I believe I have the same problem. Autocompletion suddenly just stops in all python files. No popup shows up. Here's the log: https://gist.github.com/vasa-chi/d02a2a48b7bb3efb7784

`Pending requests: Object {}` has _a lot_ of fields actually.

**Comment by silentsokolov** [comment]
+1
But, on Mac OS

**Comment by sadovnychyi** [comment]
`Pending requests: Object {}` is ok to be empty I think, this means that Jedi responds fast and there are no any requests in queue.
Does log getting populated when it *stop* working already?
I still have no clue about this issue and going to be busy in Boston for whole week.. Wasteland, you know.

**Comment by vasa-chi** [comment]
@sadovnychyi it just renders as empty ({}). When i open it, it has a lot of fields like `a233b5b00c08409a4c671cc969e747f2: function()`

**Comment by sadovnychyi** [comment]
@vasa-chi and you still can see these pending requests when autocomplete stop working? – then yeah. its likely to be a problem on python side

**Comment by FTCr** [comment]
> Can you reproduce this on specific code snippet or its just happens
> randomly?

No, I cannot. It happens randomly.

**Comment by silentsokolov** [comment]
Maybe this memory leaks? Start script (completion.py) ~10Mb, after working for a few hour: ~200Mb. If used memory > 210Mb - autocomplete stops.

Testing 3 times.

**Comment by sadovnychyi** [comment]
Just try to kill python process, it should respawn new one once you will try to complete something.

**Comment by silentsokolov** [comment]
hotfix, it not best solution :( , but it works

```python
def watch(self):
    start_time = datetime.now() + timedelta(minutes=N)

    while True:
        if not start_time > datetime.now():
            break
        try:
            self._process_request(self._input.readline())
        except Exception:
            sys.stderr.write(traceback.format_exc() + '\n')
```

**Comment by silentsokolov** [comment]
Maybe add ...

```coffee
   timeout = atom.config.get('autocomplete-python.RespawnTimeout') # default 0

    if timeout: # if timeout > 0
        setTimeout =>
              @provider.process.kill()
        , timeout
```

Be able to kill the process ... who wants

**Comment by sadovnychyi** [comment]
Just pushed a patch to terminate python process after 10k completions. Hope this number is reasonable.

**Comment by silentsokolov** [comment]
I experimented with this. If you stop the process on the side of a python sometimes raise error "socket is close". But thanks!

**Comment by sadovnychyi** [comment]
So, does it work properly with timeout? We probably could look on the requests queue, and if there are too many of them -- kill process as well & clean the queue.

**Comment by FTCr** [comment]
> So, does it work properly with timeout?

Yes, the last release works well. Thanks.

**Comment by sadovnychyi** [comment]
Changed timeout to 10 mins in latest release, as well as cleaning up requests queue.
