### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by vdjkelly** [sadovnychyi/autocomplete-python#113]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.10.1

### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
  at exports._errnoException (util.js:814:11)
  at Socket._writeGeneric (net.js:672:26)
  at Socket._write (net.js:691:8)
  at doWrite (_stream_writable.js:291:12)
  at writeOrBuffer (_stream_writable.js:277:5)
  at Socket.Writable.write (_stream_writable.js:206:11)
  at Socket.write (net.js:615:40)
  at [object Object].module.exports._sendRequest (C:\Users\vdjke\.atom\packages\autocomplete-python\lib\provider.coffee:118:40)
  at [object Object].module.exports.getSuggestions (C:\Users\vdjke\.atom\packages\autocomplete-python\lib\provider.coffee:225:6)
  at C:\Users\vdjke\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:286:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\vdjke\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:265:17)
  at AutocompleteManager.getSuggestionsFromProviders (C:\Users\vdjke\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\vdjke\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:252:19)
  at AutocompleteManager.findSuggestions (C:\Users\vdjke\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
  at atom-text-editor.subscriptions.add.atom.commands.add.autocomplete-plus:activate (C:\Users\vdjke\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:228:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\vdjke\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:243:29)
  at C:\Users\vdjke\AppData\Local\atom\app-1.1.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\vdjke\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\vdjke\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\vdjke\AppData\Local\atom\app-1.1.0\resources\app.asar\src\window-event-handler.js:97:20)

```

### Commands

```
  2x -5:49.7.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
 13x -4:28.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:18.1.0 grammar-selector:show (atom-text-editor.editor)
     -4:11.3.0 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -3:21.1.0 core:paste (atom-text-editor#autocomplete-python.pythonPath.editor.mini.is-focused)
     -3:20.5.0 core:undo (atom-text-editor#autocomplete-python.pythonPath.editor.mini.is-focused)
  5x -3:07.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
 14x -3:02.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:59.9.0 core:save (atom-text-editor.editor.is-focused)
  4x -2:54.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:43.4.0 application:new-file (atom-text-editor.editor.is-focused)
  4x -2:43.3.0 autocomplete-plus:activate (atom-text-editor.editor)
  3x -0:21 core:backspace (atom-text-editor.editor.is-focused)
 23x -0:19.3.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  4x -0:16.8.0 core:backspace (atom-text-editor.editor.is-focused)
 85x -0:15.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "autocomplete-python"
    ],
    "disabledPackages": [
      "autocomplete-paths",
      "linter",
      "linter-pylint"
    ]
  },
  "autocomplete-python": {
    "extraPaths": "$PROJECT/Python34/Lib/site-packages",
    "useSnippets": "all",
    "pythonExecutable": "python3"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v0.10.1
django-atom, v0.2.4
emmet, v2.3.14
file-icons, v1.6.11

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
When does this happen?

**Comment by otakuchiyan** [comment]
I'm also encountered this bug when inputting class name or method name, etc.

Atom version: 1.1.0
System: Windows 8.1 with Bing

Stack trace:
```
events.js:141
Error: write EPIPE
  at exports._errnoException (util.js:814:11)
  at Socket._writeGeneric (net.js:672:26)
  at Socket._write (net.js:691:8)
  at doWrite (_stream_writable.js:291:12)
  at writeOrBuffer (_stream_writable.js:277:5)
  at Socket.Writable.write (_stream_writable.js:206:11)
  at Socket.write (net.js:615:40)
  at [object Object].module.exports._sendRequest (C:\Users\西行寺幽玄\.atom\packages\autocomplete-python\lib\provider.coffee:120:40)
  at [object Object].module.exports.getSuggestions (C:\Users\西行寺幽玄\.atom\packages\autocomplete-python\lib\provider.coffee:228:6)
  at C:\Users\西行寺幽玄\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:286:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\西行寺幽玄\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:265:17)
  at AutocompleteManager.getSuggestionsFromProviders (C:\Users\西行寺幽玄\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\西行寺幽玄\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:252:19)
  at C:\Users\西行寺幽玄\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61
```
Installed packages:
- autocomplete-python, 0.10.3
- atomic-emacs, 0.7.4

**Comment by sadovnychyi** [comment]
Hopefully its fixed with latest update.
