### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by none-da** [sadovnychyi/autocomplete-python#118]
Traceback (most recent call last):
  File "/home/none-da/.atom/packages/autocomplete-python/lib/completion.py", line 257, in watch
    self._process_request(self._input.readline())
  File "/home/none-da/.atom/packages/autocomplete-python/lib/completion.py", line 248, in _process_request
    request.get('prefix', '')))
  File "/home/none-da/.atom/packages/autocomplete-python/lib/completion.py", line 124, in _serialize_completions
    'type': self._get_definition_type(completion),
  File "/home/none-da/.atom/packages/autocomplete-python/lib/completion.py", line 26, in _get_definition_type
    if definition.type not in ['import', 'keyword'] and is_built_in():
  File "/home/none-da/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/home/none-da/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/none-da/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "/home/none-da/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/none-da/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/home/none-da/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/none-da/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/home/none-da/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/none-da/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/home/none-da/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 316, in _do_import
    if module_path is None:
UnboundLocalError: local variable 'module_path' referenced before assignment

Using `0.10.4` version.

**Comment by sadovnychyi** [comment]
Nothing I can do about it, this is issue with Jedi.
