### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by muppetjones** [sadovnychyi/autocomplete-python#119]
**Atom Version**: 1.2.1
**System**: Mac OS X 10.10.5
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.10.4

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:141

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:268:12)
    at [object Object].module.exports._sendRequest (/Users/biiremployee/.atom/packages/autocomplete-python/lib/provider.coffee:120:40)
    at [object Object].module.exports.getSuggestions (/Users/biiremployee/.atom/packages/autocomplete-python/lib/provider.coffee:228:6)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -4:24.6.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -4:24.6.0 snippets:expand (atom-text-editor.editor.is-focused)
     -4:24.6.0 editor:indent (atom-text-editor.editor.is-focused)
     -4:16.8.0 core:backspace (atom-text-editor.editor.is-focused)
  7x -4:14.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:11.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -4:09.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:09.5.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -0:44.6.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -0:43.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:30 editor:newline (atom-text-editor.editor.is-focused)
     -0:29.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:29.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:29.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:29.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:29 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "brahalla-syntax"
    ],
    "disabledPackages": [
      "emmet",
      "nuclide-hack",
      "nuclide-hg-repository",
      "nuclide-quick-open",
      "linter-pep8",
      "hyperclick",
      "nuclide-language-hack",
      "nuclide-type-hint",
      "minimap"
    ],
    "ignoredNames": [
      ".DS_Store",
      "*.pyc",
      ".git",
      ".project",
      "__pycache__",
      ".pydevproject"
    ]
  },
  "autocomplete-python": {
    "extraPaths": "$PROJECT;/Users/biiremployee/venv/default/lib/python3.4/site-packages/;/Users/biiremployee/dev/remsci;",
    "pythonExecutable": "python3",
    "caseInsensitiveCompletion": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.18
autoclose-html, v0.19.0
autocomplete-python, v0.10.4
brahalla-syntax, v0.3.0
color-picker, v2.0.13
editor-stats, v0.17.0
jshint, v1.8.3
language-django, v0.1.1
language-r, v0.4.0
linter, v1.11.2
linter-csslint, v1.1.0
linter-flake8, v1.9.2
linter-htmlhint, v0.2.1
linter-jscs, v3.2.0
project-manager, v2.6.5
remote-edit, v1.8.22
view-tail-large-files, v0.2.1

# Dev
No dev packages
```

**Comment by muppetjones** [comment]
Just happened again. I typing a long function name (unittest) and ignored the predictions. I think the error happened when the predictions closed.

**Comment by muppetjones** [comment]
It seems to happen specifically when I'm typing function names.

**Comment by sadovnychyi** [comment]
This is because we are killing the process after some time. Should be fixed now.

**Comment by lukasz-madon** [comment]
just had it
