### ISSUE TITLE
Add external python libraries for auto-completion

### ISSUE THREAD

**Issue by ghtmtt** [sadovnychyi/autocomplete-python#132]
Hi there,
I've tried to configure the package as described in the readme, but it hasn't worked.

I'm trying to add the API of PyQt and PyQgis by adding some paths to the **External PATH**:
```
/usr/lib/python2.7/dist-packages/; /usr/share/qgis/python; /usr/lib/python2.7;

```

but nothing changes and the API are not recognized.
With other editor I was able to configure them (see a small section [here](http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/ide_debugging.html#making-eclipse-understand-the-api) for setting up the QGIS API in eclipse).
Am I missing something? 

Thanks!

**Comment by sadovnychyi** [comment]
Does other packages works installed in the same path?

**Comment by pyemma** [comment]
I have the similar problem, in the pervious version, it can give me suggestions from other package, but with the current version, there is no suggestions.

**Comment by sadovnychyi** [comment]
Well it works well for me for packages like bs4, installed in `/usr/local/lib/python2.7/site-packages`, this folder presented in extra path – I'm getting completions for it.

**Comment by ghtmtt** [comment]
Actually none of the packages in the ``/usr/lib/python2.7/dist-packages`` works for the autocompletion.
I tried also ``numpy`` but nothing happens..

**Comment by sadovnychyi** [comment]
Can you try to adjust python executable with another setting? Enable
package debug logs to see which one is exactly used. Try to use same
executable which you used to install packages.

**Comment by ghtmtt** [comment]
I left only ``/usr/lib/python2.7/dist-packages`` and enabled the logs but nothing changes and no log to report

**Comment by sadovnychyi** [comment]
There's another setting to set python executable/binary.

**Comment by ghtmtt** [comment]
so I left blank the **Python executable path** and filled with ``/usr/lib/python2.7/dist-packages`` the **Extra paths for packages**.. but nothing changes

should I change other settings too?

**Comment by sadovnychyi** [comment]
I'm saying that you should try to set `Python executable path` to something like `/usr/lib/python`, since you may have multiple python binaries, and I don't know which exactly is used. Use logs to make it clear. In theory you don't need to configure `Extra paths for packages` if you use proper executable.

**Comment by ghtmtt** [comment]
I tried to set the executable with ``/usr/bin/python`` and in a second moment with``/usr/lib/python`` but nope.. 
I don't know how can I help you with an example..

**Comment by ghtmtt** [comment]
I don't know if this could help. But setting ``/usr/share/qgis/python``, during the autocompletion I get this error:
```
Traceback (most recent call last):
  File "/home/ma7730/.atom/packages/autocomplete-python/lib/completion.py", line 265, in watch
    self._process_request(self._input.readline())
  File "/home/ma7730/.atom/packages/autocomplete-python/lib/completion.py", line 256, in _process_request
    request.get('prefix', '')))
  File "/home/ma7730/.atom/packages/autocomplete-python/lib/completion.py", line 118, in _serialize_completions
    completions = script.completions()
  File "/home/ma7730/.atom/packages/autocomplete-python/lib/jedi/api/__init__.py", line 192, in completions
    completion_names = get_completions(user_stmt, b)
  File "/home/ma7730/.atom/packages/autocomplete-python/lib/jedi/api/__init__.py", line 178, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/home/ma7730/.atom/packages/autocomplete-python/lib/jedi/api/__init__.py", line 259, in _simple_complete
    for names_dict in s.names_dicts(search_global=False):
  File "/home/ma7730/.atom/packages/autocomplete-python/lib/jedi/evaluate/representation.py", line 720, in names_dicts
    yield star_module.names_dict
AttributeError: 'NoneType' object has no attribute 'names_dict'
```

while with ``/usr/lib/python2.7/dist-packages`` I get these errors:
```
Uncaught TypeError: Cannot read property 'stdin' of undefined
/home/ma7730/.atom/packages/autocomplete-python/lib/provider.coffee:67
Hide Stack Trace
TypeError: Cannot read property 'stdin' of undefined
    at [object Object].module.exports._spawnDaemon (/home/ma7730/.atom/packages/autocomplete-python/lib/provider.coffee:67:22)
    at [object Object].module.exports._sendRequest (/home/ma7730/.atom/packages/autocomplete-python/lib/provider.coffee:162:8)
    at [object Object].module.exports.getSuggestions (/home/ma7730/.atom/packages/autocomplete-python/lib/provider.coffee:284:6)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

and 
```
/home/ma7730/.atom/packages/autocomplete-python/lib/provider.coffee:65
Hide Stack Trace
Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
    at [object Object].module.exports._spawnDaemon (/home/ma7730/.atom/packages/autocomplete-python/lib/provider.coffee:43:21)
    at [object Object].module.exports._sendRequest (/home/ma7730/.atom/packages/autocomplete-python/lib/provider.coffee:162:8)
    at [object Object].module.exports.getSuggestions (/home/ma7730/.atom/packages/autocomplete-python/lib/provider.coffee:284:6)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

Thanks for the patience!

**Comment by sadovnychyi** [comment]
Did you set path to python executable as `/usr/lib/python2.7/dist-packages`? Obviuosuly you got that error while trying to execute a *directory*.

First exception is Jedi related, and autocomplete should still work for other parts of your code.

**Comment by ghtmtt** [comment]
yes python path is now only ``/usr/lib/python2.7/dist-packages`` and still the same errors.
If I get rid of setting a PATH it seems working with ``numpy`` package for example, but not with QGIS and PyQt ones..

**Comment by ghtmtt** [comment]
some updates (maybe useful)..
the plugin works nice, **but** the external functions are not displayed if the package is imported in this way:
```
import qgis.core
```
or 
```
from qgis.core import *
```

it works nice if the package is imported with a name:
```
import qgis.core as qg
```
don't know if this is the expected behavior, if yes the issue can be closed.

Thanks for the availability

**Comment by sadovnychyi** [comment]
It will not autocomplete anything imported with `*`, I would say this is expected behaviour. 

But it should work for explic import with dot like this:
![image](https://cloud.githubusercontent.com/assets/193864/11799379/88569584-a30e-11e5-8148-95834539f105.png)

**Comment by sadovnychyi** [comment]
Still, Jedi tried to understand python code, which is not easy. It may not work completely for not pure-python libraries.

**Comment by ghtmtt** [comment]
Fine! Thanks for your patience! And, great job with this plugin!
