### ISSUE TITLE
Uncaught Error: Cannot find module 'fuzzaldrin'

### ISSUE THREAD

**Issue by chuckbutler** [sadovnychyi/autocomplete-python#139]
**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.2
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v1.2.2

### Stack Trace

Uncaught Error: Cannot find module 'fuzzaldrin'

```
At module.js:338

Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at _this.requests.(anonymous function) (/Users/lazy/.atom/packages/autocomplete-python/lib/provider.coffee:228:5)
    at [object Object].module.exports._deserialize (/Users/lazy/.atom/packages/autocomplete-python/lib/provider.coffee:157:9)
    at provider.BufferedProcess.stdout (/Users/lazy/.atom/packages/autocomplete-python/lib/provider.coffee:59:15)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:85:13)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "autocomplete-python": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v1.2.2

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
Try to reinstall the package.
