### ISSUE TITLE
KeyError on search

### ISSUE THREAD

**Issue by vasa-chi** [sadovnychyi/autocomplete-python#141]
When I write python files, at some point I start getting these errors on almost every character:

```
autocomplete-python: Pending requests: 9 Object {}
log.coffee:5 autocomplete-python: autocomplete-python traceback output: Traceback (most recent call last):
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/completion.py", line 265, in watch
    self._process_request(self._input.readline())
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/completion.py", line 256, in _process_request
    request.get('prefix', '')))
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/completion.py", line 123, in _serialize_completions
    description = completion.docstring()
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 449, in docstring
    followed = self._follow_statements_imports()
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 347, in _do_import
    module = _load_module(self._evaluator, module_path, source, sys_path)
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 450, in _load_module
    module = load(source) if cached is None else cached.module
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 445, in load
    p = fast.FastParser(evaluator.grammar, common.source_to_unicode(source), p)
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/parser/fast.py", line 112, in __call__
    p = super(CachedFastParser, self).__call__(grammar, source, module_path)
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/parser/fast.py", line 249, in __init__
    self.update(source)
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/parser/fast.py", line 263, in update
    self._parse(source)
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/parser/fast.py", line 403, in _parse
    line_offset, nodes)
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/parser/fast.py", line 441, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/parser/pgen2/parse.py", line 105, in parse
    for type, value, prefix, start_pos in tokenizer:
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/jedi/parser/__init__.py", line 343, in _tokenize
    typ = token.opmap[value]
KeyError: u'\xd0\xbe\xd0'
```

**Comment by sadovnychyi** [comment]
I guess you have `Output provider errors` setting set to True, right?
This is pure Jedi issue, no way I can fix it. So solution is only to hide it by unchecking that option.

**Comment by vasa-chi** [comment]
Oh! Wow, that fixed it, thanks :)
