### ISSUE TITLE
Uncaught Error: Cannot find module 'fuzzaldrin'

### ISSUE THREAD

**Issue by DWiechert** [sadovnychyi/autocomplete-python#144]
I'm getting this error anytime the editor is trying to auto-complete python code:
```
Error: Cannot find module 'fuzzaldrin'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at _this.requests.(anonymous function) (/home/dan/.atom/packages/autocomplete-python/lib/provider.coffee:228:5)
  at [object Object].module.exports._deserialize (/home/dan/.atom/packages/autocomplete-python/lib/provider.coffee:203:13)
  at provider.BufferedProcess.stdout (/home/dan/.atom/packages/autocomplete-python/lib/provider.coffee:59:15)
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:85:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:520:20)
```

**Comment by DWiechert** [comment]
I disabled and re-enabled the plugin and it seems to now be working.

**Comment by dansondergaard** [comment]
I get this error too and disabling/enabling doesn't fix it. Running Atom 1.8.0. Any hints?

**Comment by sadovnychyi** [comment]
Try to reinstall the plugin, or go to ~/.atom/packages/autocomplete-python and run `apm install` and/or `npm install`. This is due to dependencies not being installed, more like Atom/apm issue, not this package.

**Comment by dansondergaard** [comment]
Thanks, that worked :)
