### ISSUE TITLE
crash on ctrl-space bar (KeyError: <Name: deprecate@219,11>)

### ISSUE THREAD

**Issue by ramAdam** [sadovnychyi/autocomplete-python#150]
Traceback (most recent call last):
  File "/home/dev/.atom/packages/autocomplete-python/lib/completion.py", line 265, in watch
    self._process_request(self._input.readline())
  File "/home/dev/.atom/packages/autocomplete-python/lib/completion.py", line 256, in _process_request
    request.get('prefix', '')))
  File "/home/dev/.atom/packages/autocomplete-python/lib/completion.py", line 123, in _serialize_completions
    description = completion.docstring()
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 449, in docstring
    followed = self._follow_statements_imports()
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/recursion.py", line 23, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/__init__.py", line 135, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/__init__.py", line 259, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/__init__.py", line 299, in execute
    types = func(self, arguments)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/_compatibility.py", line 124, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/representation.py", line 560, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/representation.py", line 591, in __init__
    new_func = helpers.deep_ast_copy(base.base_func, self, self._copy_dict)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/helpers.py", line 64, in deep_ast_copy
    new_obj = copy_node(obj)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/helpers.py", line 38, in copy_node
    new_child = copy_node(child)
  File "/home/dev/.atom/packages/autocomplete-python/lib/jedi/evaluate/helpers.py", line 55, in copy_node
    new_names_dict[string] = [new_elements[n] for n in names]
KeyError: <Name: deprecate@219,11>

**Comment by sadovnychyi** [comment]
> I guess you have Output provider errors setting set to True, right?
> This is pure Jedi issue, no way I can fix it. So solution is only to hide it by unchecking that option.
