### ISSUE TITLE
AttributeError: 'Lambda' object has no attribute 'get_subscope_by_name'

### ISSUE THREAD

**Issue by catb0t** [sadovnychyi/autocomplete-python#151]
<pre><code>Traceback (most recent call last):
  File "/home/cat/.atom/packages/autocomplete-python/lib/completion.py", line 265, in watch
    self._process_request(self._input.readline())
  File "/home/cat/.atom/packages/autocomplete-python/lib/completion.py", line 256, in _process_request
    request.get('prefix', '')))
  File "/home/cat/.atom/packages/autocomplete-python/lib/completion.py", line 85, in _serialize_completions
    for pos, param in enumerate(call_signature.params):
  File "/home/cat/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/cat/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 348, in params
    sub = followed.get_subscope_by_name('__init__')
  File "/home/cat/.atom/packages/autocomplete-python/lib/jedi/evaluate/representation.py", line 563, in __getattr__
    return getattr(self.base_func, name)
AttributeError: 'Lambda' object has no attribute 'get_subscope_by_name'</code></pre>

When typing the name of a user-defined lambda function call  into the editor, this is thrown.

I can reproduce this by defining a lambda, then typing its call like `mylambda()`.

**Comment by sadovnychyi** [comment]
This is bug in Jedi. Please uncheck `Output provider errors` in package settings to hide such errors.
