### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stdin' of undefined

### ISSUE THREAD

**Issue by alsoicode** [sadovnychyi/autocomplete-python#152]
[Enter steps to reproduce below:]

1. Start typing. Even assigning a simple variable will trigger this exception.

**Atom Version**: 1.3.3
**System**: Ubuntu 15.10
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v1.2.4

### Stack Trace

Uncaught TypeError: Cannot read property 'stdin' of undefined

```
At /home/btaylor/.atom/packages/autocomplete-python/lib/provider.coffee:67

TypeError: Cannot read property 'stdin' of undefined
    at [object Object].module.exports._spawnDaemon (/home/btaylor/.atom/packages/autocomplete-python/lib/provider.coffee:67:22)
    at [object Object].module.exports._sendRequest (/home/btaylor/.atom/packages/autocomplete-python/lib/provider.coffee:162:8)
    at [object Object].module.exports.getSuggestions (/home/btaylor/.atom/packages/autocomplete-python/lib/provider.coffee:284:6)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -0:05.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:04.7.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "ignoredNames": [
      "*.pyc",
      "*.git",
      "*.idea",
      "*.vagrant"
    ],
    "disabledPackages": [
      "linter-pep8"
    ]
  },
  "autocomplete-python": {
    "addDotAfterModule": true,
    "addBracketAfterFunction": true,
    "pythonPaths": "$PROJECT/virtualenv",
    "extraPaths": "$PROJECT"
  }
}
```

### Installed Packages

```coffee
# User
atom-django, v0.3.2
atom-jade, v0.3.0
atom-ternjs, v0.12.2
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
autocomplete-modules, v1.3.1
autocomplete-python, v1.2.4
django-templates, v0.5.0
file-icons, v1.6.13
highlight-selected, v0.11.1
language-dotenv, v1.0.0
linter, v1.11.3
linter-jshint, v1.2.2
linter-pylint, v1.2.0
minimap, v4.19.0
minimap-bookmarks, v0.2.0
project-manager, v2.7.1
seti-syntax, v0.4.1
seti-ui, v0.8.1
symbols-tree-view, v0.11.0

# Dev
No dev packages
```

**Comment by alsoicode** [comment]
Apologies. This error must have been caused by a misconfiguration on my part.
