### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by alsoicode** [sadovnychyi/autocomplete-python#153]
[Enter steps to reproduce below:]

1. Start typing. Assign a variable, etc.

**Atom Version**: 1.3.3
**System**: Ubuntu 15.10
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v1.2.4

### Stack Trace

Uncaught Error: spawn EACCES

```
At /home/btaylor/.atom/packages/autocomplete-python/lib/provider.coffee:65

Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:351:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:188:44)
    at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
    at [object Object].module.exports._spawnDaemon (/home/btaylor/.atom/packages/autocomplete-python/lib/provider.coffee:43:21)
    at [object Object].module.exports._sendRequest (/home/btaylor/.atom/packages/autocomplete-python/lib/provider.coffee:162:8)
    at [object Object].module.exports.getSuggestions (/home/btaylor/.atom/packages/autocomplete-python/lib/provider.coffee:284:6)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -0:06.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:05.2.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "ignoredNames": [
      "*.pyc",
      "*.git",
      "*.idea",
      "*.vagrant"
    ],
    "disabledPackages": [
      "linter-pep8"
    ]
  },
  "autocomplete-python": {
    "addDotAfterModule": true,
    "addBracketAfterFunction": true,
    "pythonPaths": "$PROJECT/virtualenv",
    "extraPaths": "$PROJECT"
  }
}
```

### Installed Packages

```coffee
# User
atom-django, v0.3.2
atom-jade, v0.3.0
atom-ternjs, v0.12.2
auto-detect-indentation, v0.4.2
autoclose-html, v0.19.0
autocomplete-modules, v1.3.1
autocomplete-python, v1.2.4
django-templates, v0.5.0
file-icons, v1.6.13
highlight-selected, v0.11.1
language-dotenv, v1.0.0
linter, v1.11.3
linter-jshint, v1.2.2
linter-pylint, v1.2.0
minimap, v4.19.0
minimap-bookmarks, v0.2.0
project-manager, v2.7.1
seti-syntax, v0.4.1
seti-ui, v0.8.1
symbols-tree-view, v0.11.0

# Dev
No dev packages
```

**Comment by alsoicode** [comment]
Apologies. This error must have been caused by a misconfiguration on my part.

**Comment by gutmann** [comment]
Any idea what the misconfiguration was?  I'm getting this error too and would love to know where to start looking (or ideally the package could print more helpful error information in this case).

**Comment by alsoicode** [comment]
Hi Ethan. I can't remember exactly what it was, but it was something around the `extraPaths` parameter if I'm not mistaken. I switched it to:

    $PROJECT/virtualenv/lib/python2.7/site-packages

and it's been happy since. Hope that helps you out.

**Comment by gutmann** [comment]
Thanks! I just cleared my extra paths, and all seems to work again.  I'll try adding them one at a time and see if I can find anything more.

**Comment by alsoicode** [comment]
Kewl. I move to Atom from Sublime, where I used Anaconda, and could set a per-project Python Path. The closest I could find in Atom was this plugin and then symlinking my virtualenv into my project directory. Not as convenient, or as powerful as Anaconda, but for most things I do it works out pretty well.

**Comment by sadovnychyi** [comment]
`spawn EACCES` means that it's definitely something wrong with permissions. Whether with python executable, or maybe one of external packages. You may try to turn on debug logging which may give you more information.
