### ISSUE TITLE
PyQt5 is not being recognized

### ISSUE THREAD

**Issue by cperezabo** [sadovnychyi/autocomplete-python#16]
Hi, as the title says, the PyQt module is not being recognized by the autocompleter.
When I type **from PyQ*** nothing is listed... 
I work with that library. How can I do to get it working?

**Comment by sadovnychyi** [comment]
Are other installed packages are visible? Are you sure that Atom uses the same python executable where the PyQt5 is installed?

I recommend you to take a look into this two options:

![image](https://cloud.githubusercontent.com/assets/193864/7953047/90987a34-09f1-11e5-832c-fe65fefa095a.png)

Try to point the plugin to exact path where your python executable is located (with PyQt5 installed), or try to add the directory where PyQt5 package is located.

**Comment by cperezabo** [comment]
Hi, the python interpreter I use is at `/usr/local/Cellar/python3/3.4.3/bin`
I have set that up! 
Could it be related to the lack of implementation of virtual environment in my projects? I work directly over the base instalation

**Comment by sadovnychyi** [comment]
It should work fine without virtualenv. Try to add an extra path pointing on your site-packages directory (pyqt should be inside of that dir).

**Comment by cperezabo** [comment]
Ok, now it find not only PyQt5 but the rest of my installed modules. The problem is that all modules are being autocompleted fine but the PyQt5 one doesn't.

When I type I get
```
Traceback (most recent call last):
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/completion.py", line 151, in _process_request
    completions = script.completions()
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/api/__init__.py", line 192, in completions
    completion_names = get_completions(user_stmt, b)
```

```
File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/api/__init__.py", line 178, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/api/__init__.py", line 259, in _simple_complete
    for names_dict in s.names_dicts(search_global=False):
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 43, in wrapper
    rv = list(rv)
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/evaluate/representation.py", line 189, in names_dicts
    for s in self.base.py__mro__(self._evaluator)[1:]:
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
```

```
    rv = function(obj, *args, **kwargs)
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/evaluate/representation.py", line 429, in py__mro__
    for cls_new in mro_method(evaluator):
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/evaluate/representation.py", line 409, in py__mro__
    for cls in self.py__bases__(self._evaluator):
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/evaluate/representation.py", line 438, in py__bases__
    return list(chain.from_iterable(args.eval_args()))
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/evaluate/param.py", line 151, in eval_args
    return [self._evaluator.eval_element(el) for stars, el in self._split()]
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/evaluate/__init__.py", line 187, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/evaluate/__init__.py", line 257, in eval_trailer
    new_types += self.find_types(typ, node)
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/evaluate/__init__.py", line 117, in find_types
    scopes = f.scopes(search_global)
  File "/Users/Cristian/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 109, in scopes
    return ((n, None) for n in self.scope.names_dicts(search_global))
AttributeError: 'NoneType' object has no attribute 'names_dicts'
``

That are the tracebacks output

**Comment by sadovnychyi** [comment]
I'll take a look on that traceback tomorrow, but its likely to be Jedi's
issue so not sure that I'll be able to fix it.

**Comment by cperezabo** [comment]
Ok thanks.
I have installed PyQt5 + Qt through homebrew by the way, but I think it has nothing to do with the issue since my project is executing fine.

**Comment by cperezabo** [comment]
If you determinate that this is a Jedi's issue I can open a topic there to get it fixit upstream taking in account that you based the autocomplete-python on jedi

**Comment by sadovnychyi** [comment]
Possible related issue davidhalter/jedi#575
