### ISSUE TITLE
Uncaught SyntaxError: Unexpected token H

### ISSUE THREAD

**Issue by mohd-ahsan-mirza** [sadovnychyi/autocomplete-python#164]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Microsoft Windows 8.1
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v1.4.3

### Stack Trace

Uncaught SyntaxError: Unexpected token H

```
At file:///C:/Users/Ahsan/AppData/Local/atom/app-1.4.0/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22C%3A%5C%5CUsers%5C%5CAhsan%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22windowInitializationScript%22%3A%22C%3A%5C%5CUsers%5C%5CAhsan%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.4.0%5C%5Cresources%5C%5Capp.asar%5C%5Csrc%5C%5Cinitialize-application-window.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5CAhsan%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-1.4.0%5C%5Cresources%5C%5Capp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%221.4.0%22%2C%22atomHome%22%3A%22C%3A%5C%5CUsers%5C%5CAhsan%5C%5C.atom%22%2C%22shellLoadTime%22%3A351%2C%22initialPaths%22%3A%5B%22C%3A%5C%5CUsers%5C%5CAhsan%22%5D%7D:1

SyntaxError: Unexpected token H
    at Object.parse (native)
    at [object Object].module.exports._deserialize (file:///C:/Users/Ahsan/.atom/packages/autocomplete-python/lib/provider.coffee:169:23)
    at provider.BufferedProcess.stdout (file:///C:/Users/Ahsan/.atom/packages/autocomplete-python/lib/provider.coffee:47:10)
    at Socket.<anonymous> (C:\Users\Ahsan\AppData\Local\atom\app-1.4.0\resources\app.asar\src\buffered-process.js:85:13)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```

### Commands

```
     -2:06.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -2:05.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:04.9.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -2:04.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:44.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:36.6.0 core:move-down (atom-text-editor.editor.is-focused)
 30x -1:36.1.0 core:move-right (atom-text-editor.editor.is-focused)
  6x -1:26 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:07.1.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:05.8.0 editor:newline (atom-text-editor.editor.is-focused)
  4x -0:39.3.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:37.9.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:31.4.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:30.7.0 core:move-down (atom-text-editor.editor.is-focused)
 48x -0:09.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.8.0 core:paste (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.13
atom-react-preview, v1.2.1
autocomplete-python, v1.4.3
script, v3.4.0

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
I will close this in favor of #140. Both of this issues seems to be windows-only.
