### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stdin' of undefined

### ISSUE THREAD

**Issue by tsipinio** [sadovnychyi/autocomplete-python#173]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v1.6.1

### Stack Trace

Uncaught TypeError: Cannot read property 'stdin' of undefined

```
At /Users/pavel/.atom/packages/autocomplete-python/lib/provider.coffee:79

TypeError: Cannot read property 'stdin' of undefined
    at [object Object].module.exports._spawnDaemon (/Users/pavel/.atom/packages/autocomplete-python/lib/provider.coffee:79:22)
    at [object Object].module.exports._sendRequest (/Users/pavel/.atom/packages/autocomplete-python/lib/provider.coffee:228:8)
    at [object Object].module.exports.getSuggestions (/Users/pavel/.atom/packages/autocomplete-python/lib/provider.coffee:360:6)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:290:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:269:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:256:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
  2x -1:52.7.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -1:06.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:05.5.0 core:save (atom-text-editor.editor.is-focused)
  5x -0:40.9.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:39.8.0 editor:select-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:38.8.0 core:copy (atom-text-editor.editor.is-focused)
     -0:31.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:31.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:31.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:31.4.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:30.6.0 core:paste (atom-text-editor.editor.is-focused)
  4x -0:29.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:26 core:copy (atom-text-editor.editor.is-focused)
     -0:23.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:10.2.0 core:save (atom-text-editor.editor.is-focused)
  5x -0:07.8.0 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "*.pyc"
    ]
  },
  "autocomplete-python": {
    "pythonPaths": "$PROJECT/env/bin/"
  }
}
```

### Installed Packages

```coffee
# User
atom-django, v0.3.2
autocomplete-python, v1.6.1
color-picker, v2.1.1
django-templates, v0.5.0
file-type-icons, v0.7.4
linter, v1.11.3
linter-coffeescript, v1.0.0
linter-flake8, v1.10.1
pigments, v0.23.1
python-autopep8, v0.1.3
python-isort, v0.0.7
python-tools, v0.6.7

# Dev
No dev packages
```

**Comment by gutmann** [comment]
For what it's worth, I had this error as well, and removing all of my specified extra paths in the config made it go away.  I've been adding back paths and haven't been able to recreate the error yet though.

**Comment by Karunamon** [comment]
This is happening to me as well, except I don't have any extra paths.

**Comment by amirrustam** [comment]
Just go this error and here is the stack trace:

[Enter steps to reproduce below:]

1. Added space after a python import statement. Which triggers a flake8 PEP8 W291 trailing whitespace warning. The error occurs immediately after entering the trailing whitespace.

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v1.6.1


### Stack Trace

Uncaught TypeError: Cannot read property 'stdin' of undefined

```
At /Users/Amir/.atom/packages/autocomplete-python/lib/provider.coffee:79

TypeError: Cannot read property 'stdin' of undefined
    at [object Object].module.exports._spawnDaemon (/Users/Amir/.atom/packages/autocomplete-python/lib/provider.coffee:79:22)
    at [object Object].module.exports._sendRequest (/Users/Amir/.atom/packages/autocomplete-python/lib/provider.coffee:228:8)
    at [object Object].module.exports.getSuggestions (/Users/Amir/.atom/packages/autocomplete-python/lib/provider.coffee:360:6)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:290:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:269:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:256:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -5:12.5.0 tree-view:open-selected-entry-right (span.name.icon.icon-file-text)
     -0:58.9.0 core:undo (atom-text-editor.editor.is-focused)
     -0:38.2.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "language-python"
    ]
  },
  "autocomplete-python": {
    "pythonPaths": "/Users/Amir/Development/venv/bin",
    "useSnippets": "all"
  }
}
```

### Installed Packages

```coffee
# User
MagicPython, v0.5.8
autocomplete-python, v1.6.1
autocomplete-sass, v0.1.0
color-picker, v2.1.1
jsformat, v0.9.0
language-ansible, v0.1.3
linter, v1.11.3
linter-ansible-linting, v1.1.0
linter-flake8, v1.12.0
linter-jshint, v2.0.2
linter-markdown, v1.5.0
linter-raml, v0.2.2
linter-sass-lint, v1.1.1
markdown-mindmap, v0.2.4
markdown-preview-plus, v2.2.2
markdown-scroll-sync, v2.1.2
pigments, v0.24.1
project-manager, v2.7.6
python-indent, v0.3.4
python-iresolve, v0.0.3
python-isort, v0.0.7
python-tools, v0.6.7
raml, v0.2.0
sass-comment, v1.4.0
tidy-markdown, v1.0.0

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
Should be fixed with next release.
