### ISSUE TITLE
Exceptions from v0.4.2 in Atom 0.210.0

### ISSUE THREAD

**Issue by muppetjones** [sadovnychyi/autocomplete-python#19]
I've been getting multiples of these messages since I updated. I *think* it happens when editing in the middle of text versus typing out new code:
   `def function_<cursor_here>_name(something):` vs `def functi<cursor_here>`

```python
autocomplete-python traceback output:
Traceback (most recent call last):
  File "${HOME}/.atom/packages/autocomplete-python/lib/completion.py", line 151, in _process_request
```

```python
autocomplete-python traceback output:
    completions = script.completions()
  File "${HOME}/.atom/packages/autocomplete-python/lib/jedi/api/__init__.py", line 192, in completions
    completion_names = get_completions(user_stmt, b)
  File "${HOME}/.atom/packages/autocomplete-python/lib/jedi/api/__init__.py", line 178, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "${HOME}/.atom/packages/autocomplete-python/lib/jedi/api/__init__.py", line 254, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "${HOME}/.atom/packages/autocomplete-python/lib/jedi/api/__init__.py", line 298, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "${HOME}/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "${HOME}/.atom/packages/autocomplete-python/lib/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "${HOME}/.atom/packages/autocomplete-python/lib/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "${HOME}/.atom/packages/autocomplete-python/lib/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "${HOME}/.atom/packages/autocomplete-python/lib/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "${HOME}/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 86, in find
    names = self.filter_name(scopes)
  File "${HOME}/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 177, in filter_name
    names = self.names_dict_lookup(names_dict, position)
  File "${HOME}/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 119, in names_dict_lookup
    names = names_dict[search_str]
  File "${HOME}/.atom/packages/autocomplete-python/lib/jedi/parser/fast.py", line 78, in __getitem__
    return list(chain.from_iterable(dct.get(value, []) for dct in self.dicts))
  File "${HOME}/.atom/packages/autocomplete-python/lib/jedi/parser/fast.py", line 78, in <genexpr>
    return list(chain.from_iterable(dct.get(value, []) for dct in self.dicts))
AttributeError: 'MergedNamesDict' object has no attribute 'get'
```

**Comment by sadovnychyi** [comment]
This is definitely a bug in JEDI. I've made such errors hidden by default in 0.4.3. But if you would like to know when/why the autocomplete does not work -- you can set outputProviderErrors to True.
