### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by simonorono** [sadovnychyi/autocomplete-python#196]
#### Steps to reproduce:
- Create a new script
- Write:
```
    import os
    os. <After the dot pres ctrl + space to show the autocomplete>
```
- The editor hangs, then (after a while), it shows this output

**Atom Version**: 1.6.0
**System**: "Manjaro Linux"
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v1.7.2

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /usr/share/atom/resources/app.asar/src/config.js:1029

RangeError: Maximum call stack size exceeded
    at new Boolean (native)
    at Object (native)
    at Object._.isObject (/usr/share/atom/resources/app.asar/node_modules/underscore-plus/node_modules/underscore/underscore.js:1021:20)
    at isPlainObject (/usr/share/atom/resources/app.asar/src/config.js:1074:14)
    at Config.module.exports.Config.deepClone (/usr/share/atom/resources/app.asar/src/config.js:683:18)
    at Config.module.exports.Config.getRawValue (/usr/share/atom/resources/app.asar/src/config.js:587:22)
    at Config.module.exports.Config.get (/usr/share/atom/resources/app.asar/src/config.js:181:21)
    at Object.module.exports.debug (/home/simonorono/.atom/packages/autocomplete-python/lib/log.coffee:4:20)
    at Object.module.exports.getInterpreter (/home/simonorono/.atom/packages/autocomplete-python/lib/interpreters-lookup.coffee:72:11)
    at [object Object].module.exports._spawnDaemon (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:45:37)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:246:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
    at [object Object].module.exports._sendRequest (/home/simonorono/.atom/packages/autocomplete-python/lib/provider.coffee:247:8)
```

### Commands

```
  2x -2:03.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:58.2.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "autocomplete-python": {
    "pythonPaths": "/home/simonorono/Code/senv/bin"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.8.9
autocomplete-go, v1.0.5
autocomplete-python, v1.7.2
builder-go, v1.0.0
clang-format, v1.25.0
environment, v1.2.0
go-config, v1.1.2
go-get, v1.0.2
go-plus, v4.1.0
gofmt, v1.1.3
gometalinter-linter, v1.1.0
gorename, v1.0.0
jshint, v1.8.3
language-bison, v1.0.0
language-cmake, v0.1.4
language-flex, v0.3.0
language-lex-flex, v0.1.0
language-llvm, v0.1.1
linter, v1.11.4
linter-clang, v3.4.4
linter-pep8, v1.2.1
navigator-godef, v1.0.2
tabs-to-spaces, v1.0.2
tester-go, v1.0.3

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
Try to update package setting and set path to python executable to something like `/home/simonorono/Code/senv/bin/python`

**Comment by simonorono** [comment]
That worked. Thanks!
