### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by simonorono** [sadovnychyi/autocomplete-python#2]
[Enter steps to reproduce below:]

1. Press Ctrl + Alt + Space to open the suggestion box

**Atom Version**: 0.194.0
**System**: linux 4.0.0-1-MANJARO
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.1.5

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:141

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:275:12)
    at PythonProvider.module.exports.PythonProvider.getSuggestions (/home/simonorono/.atom/packages/autocomplete-python/lib/python-provider.coffee:72:27)
    at /home/simonorono/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:235:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/home/simonorono/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:217:17)
    at AutocompleteManager.getSuggestionsFromProviders (/home/simonorono/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/home/simonorono/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:205:19)
    at AutocompleteManager.findSuggestions (/home/simonorono/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:3:61)
    at atom-text-editor.subscriptions.add.atom.commands.add.autocomplete-plus:activate (/home/simonorono/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:181:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
```

### Commands

```
     -0:07.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:06.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "git-diff",
      "linter-flake8",
      "linter-clang",
      "linter"
    ],
    "excludeVcsIgnoredPaths": false,
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "autocomplete-python": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.12.1
autocomplete-python, v0.1.5
go-plus, v3.3.9

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
Can you check it with 0.2.0 please? I've added python 3 support and better error handling. It worked well on fresh windows and OS X, cannot test it on linux for now.

**Comment by k4nar** [comment]
I had this error with `0.1.x` due to Python 3 incompatibility on Archlinux (similar to Manjaro). It works fine with version `0.2.0`.

**Comment by simonorono** [comment]
Sorry for the late response. I'm now using version 0.3.0 and this doesn't happen anymore. Thank you very much.
