### ISSUE TITLE
Errors when using asyncio

### ISSUE THREAD

**Issue by vasa-chi** [sadovnychyi/autocomplete-python#207]
When I write code with asyncio.coroutine, autocomplete errors on `@asyncio.<cursor here>`

Traceback:
```
autocomplete-python traceback output:
Traceback (most recent call last):
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/completion.py", line 340, in watch
    self._process_request(self._input.readline())
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/completion.py", line 331, in _process_request
    request.get('prefix', '')))
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/completion.py", line 144, in _serialize_completions
    description = self._generate_signature(completion)
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/completion.py", line 68, in _generate_signature
    ', '.join(param.description for param in completion.params))
  File "/Users/vasa/.atom/packages/autocomplete-python/lib/completion.py", line 68, in <genexpr>
    ', '.join(param.description for param in completion.params))
AttributeError: 'NoneType' object has no attribute 'description'
```

**Comment by sadovnychyi** [comment]
Works for me though. (before fix)
![image](https://cloud.githubusercontent.com/assets/193864/15314572/56db2640-1c45-11e6-8926-ee8f4818a81e.png)

Fixed it anyway.

**Comment by vasa-chi** [comment]
Thank you 👍
