### ISSUE TITLE
Error while autocomplete-ing

### ISSUE THREAD

**Issue by nmiculinic** [sadovnychyi/autocomplete-python#212]
I'm trying to autocomplete tensorflow library and error pops out. Minimal code to reproduce is:

```
import tensorflow as tf
tf.<activate autocomplete>
```

tensorflow works normally in jupyter notebook (autocompletion too) and in python scripts. I'm using python 3.5 

Error log:
```
Traceback (most recent call last):
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/_compatibility.py", line 24, in find_module_py33
    loader = importlib.find_loader(string)
  File "/usr/lib/python3.5/importlib/__init__.py", line 87, in find_loader
    raise ValueError('{}.__loader__ is None'.format(name))
ValueError: google.__loader__ is None
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/lpp/.atom/packages/autocomplete-python/lib/completion.py", line 340, in watch
    self._process_request(self._input.readline())
  File "/home/lpp/.atom/packages/autocomplete-python/lib/completion.py", line 331, in _process_request
    request.get('prefix', '')))
  File "/home/lpp/.atom/packages/autocomplete-python/lib/completion.py", line 142, in _serialize_completions
    description = completion.docstring()
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 449, in docstring
    followed = self._follow_statements_imports()
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 281, in _do_import
    bases = self._do_import(import_path[:-1], sys_path)
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 327, in _do_import
    find_module(import_parts[-1])
  File "/home/lpp/.atom/packages/autocomplete-python/lib/jedi/_compatibility.py", line 28, in find_module_py33
    raise ImportError("Originally ValueError: " + e.message)
AttributeError: 'ValueError' object has no attribute 'message'
```

**Comment by sadovnychyi** [comment]
You are better to report it directly to Jedi.

https://github.com/davidhalter/jedi

**Comment by sadovnychyi** [comment]
https://github.com/jorgenschaefer/elpy/issues/873
Maybe also related https://github.com/davidhalter/jedi/issues/122

**Comment by nmiculinic** [comment]
I've reported in to jedi davidhalter/jedi#730

In the meantime, I've also opened issue with autocomplete-plus ( atom/autocomplete-plus#727 ) since error in autocomplete-python provider kills all other providers (default/snippets/most recent/hydrogen). The last one is visible when I disable autocomplete-python and use completions from hydrogen.

Can I somehow in autocomplete-python ignore errors, that is only logging them, and providing no suggestions to autocomplete-plus?

**Comment by sadovnychyi** [comment]
The message you received said:

```
Looks like this error originated from Jedi. Please do not
report such issues in autocomplete-python issue tracker. Report
them directly to Jedi. Turn off `outputProviderErrors` setting
to hide such errors in future. 
```

It's possible that you will encounter any coffeescript related errors and they will still show up, but this is rare.

**Comment by nmiculinic** [comment]
You're right, it said that.

I checked dev tools and cannot see any other errors related to autocomplete-python. Nevertheless it kills all other providers in my case.

**Comment by sadovnychyi** [comment]
Yeah, probably because when we catch an exception we don't know from which request did it come, and that promise (autocomplete-plus relies on that promise) keeps in unresolved state forever.

I think it's possible to watch for unresolved promises and try to resolve them with empty response after specific time out, but it will not give you any smooth experience anyway.

This problem should be resolved in autocomplete-plus, not here.

**Comment by nmiculinic** [comment]
> Yeah, probably because when we catch an exception we don't know from which request did it come, and that promise (autocomplete-plus relies on that promise) keeps in unresolved state forever.

Can you on exception close all open promises with empty response from autocomplete-python? Since in autocomplete experience I'm most interested in the latest autocomplete suggestion (I have system image in my head where you async send requests to jedi whenever autocomplete is requested in promise form. Thus multiple autocomplete-python requests could be pending to Jedi at same time. Please correct me if I'm wrong)

This would give smother experience if Jedi throws exception.

**Comment by sadovnychyi** [comment]
Correct, we may have multiple requests to Jedi at the same time.
Maybe you are right if under the hood we will force to close all of them in case of (hopefully rare) exception occurrence. 
I'll take a look.

**Comment by sadovnychyi** [comment]
Try 1.7.5 release.

**Comment by sadovnychyi** [comment]
I hope this change will not conflict with other features like go-to-definition or rename.

**Comment by nmiculinic** [comment]
I've tried it and it works!

On tensorflow example now I have hydrogen autocomplete suggestions when jedi errors.

Thank you!

**Comment by sadovnychyi** [comment]
Ok, hopefully the issue will be fixed in Jedi as well.
