### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by pashifika** [sadovnychyi/autocomplete-python#28]
OS: Windows 8.1 x64
language: JA
Python 3.4.3

Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
UnicodeDecodeError: 'cp932' codec can't decode byte 0x83 in position 504: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
UnicodeDecodeError: 'cp932' codec can't decode byte 0x87 in position 204: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 143, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 116, in _deserialize
    return json.loads(request)
  File "D:\WinPython-64bit-34\python-3.4.3.amd64\Lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "D:\WinPython-64bit-34\python-3.4.3.amd64\Lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\WinPython-64bit-34\python-3.4.3.amd64\Lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
UnicodeDecodeError: 'cp932' codec can't decode byte 0x83 in position 505: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
UnicodeDecodeError: 'cp932' codec can't decode byte 0x87 in position 205: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 143, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 116, in _deserialize
    return json.loads(request)
  File "D:\WinPython-64bit-34\python-3.4.3.amd64\Lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "D:\WinPython-64bit-34\python-3.4.3.amd64\Lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\WinPython-64bit-34\python-3.4.3.amd64\Lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
UnicodeDecodeError: 'cp932' codec can't decode byte 0x83 in position 504: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
UnicodeDecodeError: 'cp932' codec can't decode byte 0x87 in position 204: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 143, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 116, in _deserialize
    return json.loads(request)
  File "D:\WinPython-64bit-34\python-3.4.3.amd64\Lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "D:\WinPython-64bit-34\python-3.4.3.amd64\Lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\WinPython-64bit-34\python-3.4.3.amd64\Lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
UnicodeDecodeError: 'cp932' codec can't decode byte 0x83 in position 504: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
UnicodeDecodeError: 'cp932' codec can't decode byte 0x87 in position 204: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 143, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 116, in _deserialize
    return json.loads(request)
  File "D:\WinPython-64bit-34\python-3.4.3.amd64\Lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "D:\WinPython-64bit-34\python-3.4.3.amd64\Lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\WinPython-64bit-34\python-3.4.3.amd64\Lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
UnicodeDecodeError: 'cp932' codec can't decode byte 0x83 in position 505: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
UnicodeDecodeError: 'cp932' codec can't decode byte 0x87 in position 205: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 143, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 116, in _deserialize
    return json.loads(request)
  File "D:\WinPython-64bit-34\python-3.4.3.amd64\Lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "D:\WinPython-64bit-34\python-3.4.3.amd64\Lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\WinPython-64bit-34\python-3.4.3.amd64\Lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())
UnicodeDecodeError: 'cp932' codec can't decode byte 0x83 in position 506: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 169, in watch
    self._process_request(sys.stdin.readline())

**Comment by sadovnychyi** [comment]
What did you type?

**Comment by pashifika** [comment]
OS language: JA
Python script commentline is Unicode char.

OS: Windows 8.1 x64
Python 3.4.3                          not work
Python 2.7.9                          worked

OS: Windows 10 x64
Python 3.4.3                          not work
Python 2.7.9                          worked

**Comment by sadovnychyi** [comment]
Should be fixed with 0.5.2!
