### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by RedXBeard** [sadovnychyi/autocomplete-python#30]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.5.1

### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At /Users/denizci/.atom/packages/autocomplete-python/lib/provider.coffee:85

TypeError: Cannot read property '0' of undefined
  at [object Object].module.exports._deserialize (/Users/denizci/.atom/packages/autocomplete-python/lib/provider.coffee:85:6)
  at Interface.<anonymous> (/Users/denizci/.atom/packages/autocomplete-python/lib/provider.coffee:78:41)
  at emitOne (events.js:77:13)
  at Interface.emit (events.js:166:7)
  at Interface._onLine (readline.js:195:10)
  at Interface.<anonymous> (readline.js:325:12)
  at Array.forEach (native)
  at Interface._normalWrite (readline.js:324:11)
  at Socket.ondata (readline.js:71:10)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```

### Commands

```
  2x -0:29.6.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -0:29 core:select-left (atom-text-editor.editor.is-focused)
 15x -0:27.5.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -0:26 core:select-right (atom-text-editor.editor.is-focused)
     -0:24.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:24.2.0 core:select-right (atom-text-editor.editor.is-focused)
  3x -0:23.8.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:22.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:22.5.0 core:select-right (atom-text-editor.editor.is-focused)
  3x -0:21.3.0 core:move-right (atom-text-editor.editor.is-focused)
  6x -0:18.3.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:11.3.0 core:move-right (atom-text-editor.editor.is-focused)
  6x -0:11 core:select-left (atom-text-editor.editor.is-focused)
     -0:02.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:02.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:00.3.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "ignoredNames": [
      ".git",
      "*.pyc",
      ".git*",
      "static",
      ".DS_*"
    ],
    "disabledPackages": [
      "linter-pep8",
      "atom-django"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-dlang, v1.1.2
autocomplete-python, v0.5.1
language-ini, v1.10.0
language-swift, v0.4.0
linter, v1.1.0
linter-flake8, v1.4.2

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
Any steps to reproduce this?
