### ISSUE TITLE
Autocomplete error when importing modules

### ISSUE THREAD

**Issue by Mactepp** [sadovnychyi/autocomplete-python#35]
Hi. Something strange is happening to me. When I try to import a module in a new file, it works fine, but when I try to do the same thing when editing a saved file, it does not show the modules and show an error.

This is the error:

**autocomplete-python traceback output:**

Traceback (most recent call last):
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib/completion.py", line 154, in _process_request
    completions = script.completions()
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib\jedi\api\__init__.py", line 192, in completions
    completion_names = get_completions(user_stmt, b)
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib\jedi\api\__init__.py", line 150, in get_completions
    completion_names = i.completion_names(self._evaluator, only_modules)
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib\jedi\evaluate\imports.py", line 423, in completion_names
    names += self._get_module_names()
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib\jedi\evaluate\imports.py", line 368, in _get_module_names
    for module_loader, name, is_pkg in pkgutil.iter_modules(search_path):
  File "C:\Python27\Lib\pkgutil.py", line 143, in iter_modules
    importers = map(get_importer, path)
  File "C:\Python27\Lib\pkgutil.py", line 384, in get_importer
    importer = path_hook(path_item)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-12: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib/completion.py", line 154, in _process_request
    completions = script.completions()
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib\jedi\api\__init__.py", line 192, in completions
    completion_names = get_completions(user_stmt, b)
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib\jedi\api\__init__.py", line 150, in get_completions
    completion_names = i.completion_names(self._evaluator, only_modules)
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib\jedi\evaluate\imports.py", line 423, in completion_names
    names += self._get_module_names()
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib\jedi\evaluate\imports.py", line 368, in _get_module_names
    for module_loader, name, is_pkg in pkgutil.iter_modules(search_path):
  File "C:\Python27\Lib\pkgutil.py", line 143, in iter_modules
    importers = map(get_importer, path)
  File "C:\Python27\Lib\pkgutil.py", line 384, in get_importer
    importer = path_hook(path_item)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-12: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib/completion.py", line 154, in _process_request
    completions = script.completions()
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib\jedi\api\__init__.py", line 192, in completions
    completion_names = get_completions(user_stmt, b)
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib\jedi\api\__init__.py", line 150, in get_completions
    completion_names = i.completion_names(self._evaluator, only_modules)
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib\jedi\evaluate\imports.py", line 423, in completion_names
    names += self._get_module_names()
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib\jedi\evaluate\imports.py", line 368, in _get_module_names
    for module_loader, name, is_pkg in pkgutil.iter_modules(search_path):
  File "C:\Python27\Lib\pkgutil.py", line 143, in iter_modules
    importers = map(get_importer, path)
  File "C:\Python27\Lib\pkgutil.py", line 384, in get_importer
    importer = path_hook(path_item)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-12: ordinal not in range(128)
Traceback (most recent call last):
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib/completion.py", line 154, in _process_request
    completions = script.completions()
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib\jedi\api\__init__.py", line 192, in completions
    completion_names = get_completions(user_stmt, b)
  File "C:\Users\Tulio\.atom\packages\autocomplete-python\lib\jedi\api\__init__.py", line 150, in get_completions
    completion_names = i.completion_names(self._evaluator, only_modules)

I'm new to programming, sorry if I'm reporting something stupid.

**Comment by sadovnychyi** [comment]
Looks like it's related to #28
