### ISSUE TITLE
all file not work.

### ISSUE THREAD

**Issue by pashifika** [sadovnychyi/autocomplete-python#39]
not work, please test it.
Windows 8.1 x64 JA

----------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 179, in watch
    self._process_request(self._input.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 153, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 126, in _deserialize
    return json.loads(request.encode('utf-8'))
  File "D:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 179, in watch
    self._process_request(self._input.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 153, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 126, in _deserialize
    return json.loads(request.encode('utf-8'))
  File "D:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 179, in watch
    self._process_request(self._input.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 153, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 126, in _deserialize
    return json.loads(request.encode('utf-8'))
  File "D:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 179, in watch
    self._process_request(self._input.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 153, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 126, in _deserialize
    return json.loads(request.encode('utf-8'))
  File "D:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 179, in watch
    self._process_request(self._input.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 153, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 126, in _deserialize
    return json.loads(request.encode('utf-8'))
  File "D:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 179, in watch
    self._process_request(self._input.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 153, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 126, in _deserialize
    return json.loads(request.encode('utf-8'))
  File "D:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 179, in watch
    self._process_request(self._input.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 153, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 126, in _deserialize
    return json.loads(request.encode('utf-8'))
  File "D:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 179, in watch
    self._process_request(self._input.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 153, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 126, in _deserialize
    return json.loads(request.encode('utf-8'))
  File "D:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 179, in watch
    self._process_request(self._input.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 153, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 126, in _deserialize
    return json.loads(request.encode('utf-8'))
  File "D:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 179, in watch
    self._process_request(self._input.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 153, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 126, in _deserialize
    return json.loads(request.encode('utf-8'))
  File "D:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 179, in watch
    self._process_request(self._input.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 153, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 126, in _deserialize
    return json.loads(request.encode('utf-8'))
  File "D:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 179, in watch
    self._process_request(self._input.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 153, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 126, in _deserialize
    return json.loads(request.encode('utf-8'))
  File "D:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 179, in watch
    self._process_request(self._input.readline())
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 153, in _process_request
    request = self._deserialize(request)
  File "C:\Users\Pashifika\.atom\packages\autocomplete-python\lib/completion.py", line 126, in _deserialize
    return json.loads(request.encode('utf-8'))

**Comment by sadovnychyi** [comment]
Fixed in 0.5.3. Thanks for report!
