### ISSUE TITLE
Error throw every time an opening bracket is written

### ISSUE THREAD

**Issue by driuba** [sadovnychyi/autocomplete-python#465]
### Prerequisites

* [x] Please make sure to properly [configure](https://github.com/autocomplete-python/autocomplete-python#configuration) plugin first if you simply cannot see any completions.
* [x] It's always helpful if you include debug logs with your issue:
  * Go to package settings to enable them
  ![image](https://cloud.githubusercontent.com/assets/193864/19852051/01e4e45c-9f9c-11e6-9480-dd22147c82b3.png)
  * Open `dev tools` using command palette and you should see some `autocomplete-python` records in console tab. This will include parts of your code – make sure to remove everything you don't want to share.

### Steps to Reproduce

1. Write a bracket, e. g.:  
```
variable = ()
variable = []
variable = {}
```

**Expected behavior:**  
No error to be displayed.

**Actual behavior:**  
Error is throw every time by `autocomplete-python`  
![image](https://user-images.githubusercontent.com/23050019/160409267-3acbfc09-2829-47fb-88aa-3670a3ef131f.png)

No issues with function definitions and calls, the issue seems to be triggered when single bracket is being written (like when using list comprehensions or declaring variables).

Error text:  
```
autocomplete-python traceback output:

Traceback (most recent call last):
  File "/home/driuba/.atom/packages/autocomplete-python/lib/completion.py", line 381, in watch
    self._process_request(request)
  File "/home/driuba/.atom/packages/autocomplete-python/lib/completion.py", line 349, in _process_request
    return self._write_response(self._serialize_tooltip(
  File "/home/driuba/.atom/packages/autocomplete-python/lib/completion.py", line 275, in _serialize_tooltip
    'line': definition.line - 1,
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

---

OS info:  
![image](https://user-images.githubusercontent.com/23050019/160408380-e7f9d902-3c25-4760-898d-06a45db00d5e.png)

Atom info:  
![image](https://user-images.githubusercontent.com/23050019/160408568-70fa72d1-575d-41a7-8d5f-c0484ba3e21f.png)

autocomplete-python info:  
![image](https://user-images.githubusercontent.com/23050019/160408843-45f286dd-12f4-4e27-bb6e-c4044770d423.png)

---

P. S.  
Other functionality works as expected without issues. The error message does not seem to be critical, however it is very annoying as it spams a lot.

**Comment by Danielnewheart** [comment]
I have the same problem. I use MacBook Pro 2015, Monterey 12.1, and the same version of atom.
It's really annoying to me, hoping someone can solve this problem
<img width="446" alt="截圖 2022-05-13 17 28 59" src="https://user-images.githubusercontent.com/87961226/168254741-78a50765-8117-4f15-b445-9bcb8f5a0763.png">
.
