### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by morgado-jb** [sadovnychyi/autocomplete-python#59]
1. It happens when opening Atom while loading a file from command line.

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.5.3

### Stack Trace

Uncaught SyntaxError: Unexpected end of input

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fmorgado%2FBTSync%2Fwork%2Fcicge%2Fprojectos%2Fepam%2Fcode%2Fdepo_sims%2Fsi_absorb_sim.py%22%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%221.0.11%22%2C%22shellLoadTime%22%3A336%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fmorgado%2FBTSync%2Fwork%2Fcicge%2Fprojectos%2Fepam%2Fcode%2Fdepo_sims%22%5D%7D:0

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at [object Object].module.exports._deserialize (/Users/morgado/.atom/packages/autocomplete-python/lib/provider.coffee:86:23)
    at Interface.<anonymous> (/Users/morgado/.atom/packages/autocomplete-python/lib/provider.coffee:77:24)
    at emitOne (events.js:77:13)
    at Interface.emit (events.js:166:7)
    at Interface._onLine (readline.js:195:10)
    at Interface.<anonymous> (readline.js:325:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:324:11)
    at Socket.ondata (readline.js:71:10)
```

### Commands

```
     -0:02.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "hyperclick",
      "nuclide-click-to-symbol",
      "nuclide-code-format",
      "nuclide-diff-view",
      "nuclide-file-tree",
      "nuclide-file-watcher",
      "nuclide-flow",
      "nuclide-hack",
      "nuclide-hg-repository",
      "nuclide-installer",
      "nuclide-language-hack",
      "nuclide-quick-open",
      "nuclide-remote-projects",
      "nuclide-type-hint",
      "linter-pylint"
    ],
    "themes": [
      "one-dark-ui",
      "oceanic-next"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-python, v0.5.3
keyboard-localization, v1.4.8
language-ipynb, v1.3.0
language-latex, v0.6.1
linter, v1.5.1
linter-flake8, v1.6.1
minimap, v4.13.3
oceanic-next, v0.1.2

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
Closing this as old and unreproducible.
