### ISSUE TITLE
Uncaught Error: This socket is closed.

### ISSUE THREAD

**Issue by Danielhu229** [sadovnychyi/autocomplete-python#60]
1.download and install atom on OSX 10.103
2.install package autocomplete-python
*the same issue occurs each time typing or restarting atom*

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.5.3

### Stack Trace

Uncaught Error: This socket is closed.

```
At events.js:141

Error: This socket is closed.
    at Socket._writeGeneric (net.js:634:19)
    at Socket._write (net.js:687:8)
    at doWrite (_stream_writable.js:295:12)
    at writeOrBuffer (_stream_writable.js:282:5)
    at Socket.Writable.write (_stream_writable.js:210:11)
    at Socket.write (net.js:612:40)
    at [object Object].module.exports.getSuggestions (/Users/huyiming/.atom/packages/autocomplete-python/lib/provider.coffee:132:27)
    at /Users/huyiming/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:267:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Users/huyiming/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:246:17)
```

### Commands

```
  2x -0:02.5.0 core:move-left (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "python-tools",
      "autocomplete-plus-python-jedi",
      "python-jedi"
    ]
  },
  "autocomplete-python": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v0.5.3
language-lua, v0.9.4
linter-lua, v1.0.0

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
Is there are any more errors appearing with another debug info? Do you have python installed and available in your path? Are you running atom from a command line?

**Comment by sadovnychyi** [comment]
This should be fixed when we will implement better interpreter lookup in #66.
Please watch mentioned issue for updates.
