### ISSUE TITLE
Uncaught Error: This socket is closed.

### ISSUE THREAD

**Issue by gregor77** [sadovnychyi/autocomplete-python#67]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.5.4

### Stack Trace

Uncaught Error: This socket is closed.

```
At events.js:141

Error: This socket is closed.
  at Socket._writeGeneric (net.js:637:19)
  at Socket._write (net.js:691:8)
  at doWrite (_stream_writable.js:291:12)
  at writeOrBuffer (_stream_writable.js:277:5)
  at Socket.Writable.write (_stream_writable.js:206:11)
  at Socket.write (net.js:615:40)
  at [object Object].module.exports.getSuggestions (/Users/bookboogie/.atom/packages/autocomplete-python/lib/provider.coffee:122:21)
  at /Users/bookboogie/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:267:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Users/bookboogie/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:246:17)
  at AutocompleteManager.getSuggestionsFromProviders (/Users/bookboogie/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Users/bookboogie/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:233:19)
  at /Users/bookboogie/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61

```

### Commands

```
     -1:36 tool-panel:unfocus (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -1:35.5.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -1:09.8.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:43.6.0 merge-conflicts:detect (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:30.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:30.4.0 vim-mode:move-left (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:29.9.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:29.7.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:27.9.0 vim-mode:move-to-last-character-of-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:27 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:26.4.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:07.6.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:04.4.0 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-django, v0.3.0
autocomplete-python, v0.5.4
django-templates, v0.5.0
linter-flake8, v1.6.1
merge-conflicts, v1.3.6
tree-view-git-status, v0.2.2
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
This should be fixed when we will implement better interpreter lookup in #66.
Please watch mentioned issue for updates.
