### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by muppetjones** [sadovnychyi/autocomplete-python#7]
This error is thrown whenever I type in the editor (for python files, of course).
It may be the exact same error as [this](https://github.com/sadovnychyi/autocomplete-python/issues/2), but as that issue is closed and I have the latest version (which was the solution for the linked issue), I thought I'd create a new one. 

## Stack Trace
```
Error: This socket has been ended by the other party
  at Socket.writeAfterFIN [as write] (net.js:275:12)
  at [object Object].module.exports.getSuggestions (~/.atom/packages/autocomplete-python/lib/provider.coffee:65:21)
  at ~/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:140:7
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (~/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:123:5)
  at AutocompleteManager.getSuggestionsFromProviders (~/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (~/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:123:16)
  at ~/.atom/packages/autocomplete-plus/lib/autocomplete-manager.coffee:1:1
```

## Config
```
"*":
  editor:
    invisibles: {}
    showInvisibles: true
    tabLength: 4
    zoomFontWhenCtrlScrolling: true
    fontSize: 13
    scrollPastEnd: true
    showIndentGuide: true
    softWrapAtPreferredLineLength: true
  core:
    themes: [
      "one-dark-ui"
      "one-dark-syntax"
    ]
    disabledPackages: [
      "linter-tidy"
      "linter-pep8"
    ]
  "exception-reporting":
    [ ... ]
  welcome:
    [ ... ]
  "recent-files":
    [ ... ]
  linter:
    [ ... ]
  "linter-pep8":
    [ ... ]
  "atom-beautify":
    [ ... ]
  "bracket-matcher":
    [ ... ]
  "autocomplete-plus": {}
  "autocomplete-python":
    extraPaths: "~/venv/default/bin/python"
```

## Versions
```
atom: 0.198.0
autocomplete-plus: 2.14.1
autocomplete-python: 0.3.0
python: 3.4
```

Thanks!

**Comment by sadovnychyi** [comment]
I've updated the exception handling in 0.3.1 to be more specific, not possible to debug what exactly went wrong here. If you could give me more information I'll be glad to help.

I've tested it with python 3.4 -- works fine on OSX and Windows for me.

**Comment by muppetjones** [comment]
I just updated autocomplete-plus, and the error when away. If I get it again, I'll update. For now, I think the problem is solved.

**Comment by Samcfuchs** [comment]
I still have this error whenever I add a trailing space.

**Comment by sadovnychyi** [comment]
@Samcfuchs you use the latest version of atom and autocomplete-python? Can you give me your log output from the dev console please?

**Comment by mlamby** [comment]
I also was getting this exception being thrown on Windows. Turns out it was happening because I didn't have python in my path as per the readme. Added python to my path and restarted Atom and the problem went away.

**Comment by WeiEast** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.10.4
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.5.3


### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:141

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:266:12)
    at [object Object].module.exports.getSuggestions (/Users/wdf/.atom/packages/autocomplete-python/lib/provider.coffee:119:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -4:15.1.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:14.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:11.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -4:09.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -4:03.5.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:55.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:53.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:53.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -3:52.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:48.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  7x -3:47.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:40.3.0 core:save (atom-text-editor.editor.is-focused)
     -3:28.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:27.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -3:25.7.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:25.9.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v0.5.3

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
@WeiEast v0.5.3 is really old version. Just update your package.

**Comment by JostCrow** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0-beta1
**System**: elementary OS
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.10.4


### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:141

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:268:12)
    at [object Object].module.exports._sendRequest (/home/jorik/.atom/packages/autocomplete-python/lib/provider.coffee:120:40)
    at [object Object].module.exports.getSuggestions (/home/jorik/.atom/packages/autocomplete-python/lib/provider.coffee:228:6)
    at /usr/share/atom-beta/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom-beta/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom-beta/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom-beta/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /usr/share/atom-beta/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -0:29.2.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
  5x -0:24.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:13.8.0 core:copy (atom-text-editor.editor.is-focused)
     -0:11.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:11.6.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:11.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:10.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:10.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:10 editor:move-line-up (atom-text-editor.editor.is-focused)
     -0:09.6.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:09.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:08.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:08.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:04.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:03.8.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "material-design-syntax"
    ],
    "openEmptyEditorOnStart": false,
    "autoHideMenuBar": true,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "nuclide-hg-repository"
    ]
  },
  "autocomplete-python": {
    "extraPaths": "$PROJECT/env/lib/python2.7/site-packages"
  }
}
```

### Installed Packages

```coffee
# User
api-workbench, v0.8.6
apm-publish, v0.2.8
atom-beautify, v0.28.18
atom-jade, v0.3.0
atom-material-ui, v0.8.0
autocomplete-python, v0.10.4
autohide-tree-view, v0.25.1
autoupdate-packages, v1.3.0
color-picker, v2.0.13
django-atom, v0.2.4
highlight-line, v0.11.0
hyperclick, v0.0.32
icon-fonts, v1.8.3
imdone-atom, v1.1.60
linter, v1.11.2
linter-pep8, v1.0.1
linter-pylint, v1.0.3
material-design-syntax, v1.7.0
meteor-api, v2.20.0
minimap, v4.16.0
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
pigments, v0.18.1
project-dropdown, v0.3.0
python-tools, v0.6.6
selection-highlight, v0.1.4
set-syntax, v0.3.0
seti-icons, v0.4.5
soft-wrap-indicator, v0.7.0
terminal-plus, v0.14.3
tool-bar, v0.1.9
tool-bar-shortcuts, v0.1.5

# Dev
tool-bar-shortcuts, v0.1.5
```

**Comment by muppetjones** [comment]
So...I completely forgot about this bug. I submitted a new one when it happened in the latest version:
https://github.com/sadovnychyi/autocomplete-python/issues/119
