### ISSUE TITLE
Error with custom Extra Path

### ISSUE THREAD

**Issue by heyoni** [sadovnychyi/autocomplete-python#72]
Hello,

After I added a couple of folders to the extra path field in settings, I started getting the two following errors. Immediately below is the paths I added so that I could have autocompletion for downloaded modules. Anyone know what these errors might mean and whether this is something I could fix myself?

>/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/lib-dynload;/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4;/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages

And the error log:

>autocomplete-python traceback output:
Traceback (most recent call last):
  File "/Users/user/.atom/packages/autocomplete-python/lib/completion.py", line 212, in watch
    self._process_request(self._input.readline())
  File "/Users/user/.atom/packages/autocomplete-python/lib/completion.py", line 202, in _process_request
    response = self._serialize_completions(results, request['id'])
  File "/Users/user/.atom/packages/autocomplete-python/lib/completion.py", line 105, in _serialize_completions
    'type': self._get_definition_type(completion),
Close All
autocomplete-python traceback output:
  File "/Users/user/.atom/packages/autocomplete-python/lib/completion.py", line 27, in _get_definition_type
    if definition.type not in ['import', 'keyword'] and is_built_in():
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 470, in type
    followed = self.follow_definition()
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 498, in follow_definition
    defs = self._follow_statements_imports()
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/api/classes.py", line 485, in _follow_statements_imports
    return i.follow()
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 282, in _name_to_types
    types += imports.ImportWrapper(evaluator, name).follow()
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 282, in _name_to_types
    types += imports.ImportWrapper(evaluator, name).follow()
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 282, in _name_to_types
    types += imports.ImportWrapper(evaluator, name).follow()
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 103, in follow
    for t in types))
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/imports.py", line 103, in <genexpr>
    for t in types))
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/__init__.py", line 117, in find_types
    scopes = f.scopes(search_global)
  File "/Users/user/.atom/packages/autocomplete-python/lib/jedi/evaluate/finder.py", line 109, in scopes
    return ((n, None) for n in self.scope.names_dicts(search_global))
AttributeError: 'NoneType' object has no attribute 'names_dicts'

**Comment by sadovnychyi** [comment]
I'm pretty sure this is a JEDI bug and is not related to this package. I'll try to make them less affect this package in the future.

**Comment by sadovnychyi** [comment]
So, you shouldn't be seeing this error unless you have outputProviderErrors set to True in your package settings. By default its False.
