### ISSUE TITLE
Uncaught Error: This socket is closed.

### ISSUE THREAD

**Issue by kilgharrah** [sadovnychyi/autocomplete-python#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.3.0

### Stack Trace

Uncaught Error: This socket is closed.

```
At events.js:141

Error: This socket is closed.
  at Socket._writeGeneric (net.js:634:19)
  at Socket._write (net.js:687:8)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Socket.Writable.write (_stream_writable.js:210:11)
  at Socket.write (net.js:612:40)
  at [object Object].module.exports.getSuggestions (C:\Users\Bence\.atom\packages\autocomplete-python\lib\provider.coffee:65:21)
  at C:\Users\Bence\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:254:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\Bence\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:233:17)
  at AutocompleteManager.getSuggestionsFromProviders (C:\Users\Bence\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\Bence\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:221:19)
  at C:\Users\Bence\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61

```

### Commands

```
  9x -4:25.7.0 core:backspace (div.settings-view.pane-item)
  3x -4:18.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:25.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:18.6.0 grammar-selector:show (atom-text-editor.editor)
     -0:15.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:05.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:02.8.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:02.8.0 snippets:expand (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "solarized-dark-syntax"
    ]
  },
  "autocomplete-python": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-python, v0.3.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
I've updated the exception handling in 0.3.1 to be more specific, not possible to debug what exactly went wrong here. If you could give me more information I'll be glad to help.

**Comment by batjko** [comment]
Just ran into this issue as well, after installing this package 2 minutes prior.

 1. Install autocomplete-python
 2. create new file and save it with .py extension
 3. Start typing a few characters and observe error notification.
![image](https://cloud.githubusercontent.com/assets/7287076/8709171/743c4ee8-2b38-11e5-8e2d-e949cfbfb0b3.png)

What else do you need to know?

**Comment by batjko** [comment]
Actually, nevermind... I just restarted Atom and the error does not re-appear.

**Comment by DontPanic345** [comment]
Also happened to me after install. Atom needs to be restarted after installing.
