### ISSUE TITLE
python autocomplete error

### ISSUE THREAD

**Issue by angeljz** [sadovnychyi/autocomplete-python#81]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.6.2

### Stack Trace

Failed to load the autocomplete-python package

```
At Cannot find module 'mixto'

Error: Cannot find module 'mixto'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\grim\node_modules\emissary\node_modules\property-accessors\lib\property-accessors.js:6:11)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\grim\node_modules\emissary\node_modules\property-accessors\lib\property-accessors.js:74:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\grim\node_modules\emissary\lib\behavior.js:9:23)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\grim\node_modules\emissary\lib\behavior.js:120:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\grim\node_modules\emissary\lib\helpers.js:5:14)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\grim\node_modules\emissary\lib\helpers.js:55:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\grim\node_modules\emissary\lib\emissary.js:4:13)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\grim\node_modules\emissary\lib\emissary.js:14:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\grim\lib\grim.js:4:13)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\node_modules\space-pen\node_modules\grim\lib\grim.js:105:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:10:12)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:634:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\lib\main.js:4:10)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\lib\main.js:22:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\lib\definitions-view.coffee:1:24)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\lib\definitions-view.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\lib\provider.coffee:2:19)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\lib\provider.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\lib\main.coffee:1:12)
    at Object.<anonymous> (C:\Users\Rebeca Toro\.atom\packages\autocomplete-python\lib\main.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:761:34)
    at C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:192:28
    at Package.module.exports.Package.measure (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:169:15)
    at Package.module.exports.Package.load (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:183:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:405:14)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:369:14)
    at Atom.module.exports.Atom.startEditorWindow (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\atom.js:667:21)
    at Object.<anonymous> (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-bootstrap.js:12:8)
    at Object.<anonymous> (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-bootstrap.js:23:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Rebeca Toro\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at setupWindow (file:///C:/Users/Rebeca%20Toro/AppData/Local/atom/app-1.0.19/resources/app.asar/static/index.js:82:25)
    at window.onload (file:///C:/Users/Rebeca%20Toro/AppData/Local/atom/app-1.0.19/resources/app.asar/static/index.js:35:9)
```

### Commands

```
     -0:05.5.0 core:move-right (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "autocomplete-python": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-html-entities, v0.1.0
autocomplete-python, v0.6.2
color-picker, v2.0.11
emmet, v2.3.12
file-icons, v1.6.7
file-type-icons, v0.7.3
icon-fonts, v1.4.0
minimap, v4.13.1

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
It looks like it could be a bug in apm. Try to reinstall the package.

Possible related to: Glavin001/atom-beautify#381
