### ISSUE TITLE
Uncaught SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by JostCrow** [sadovnychyi/autocomplete-python#96]
[Enter steps to reproduce below:]

1. Typing for autocompletion

**Atom Version**: 1.0.19
**System**: elementary OS
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.9.0

### Stack Trace

Uncaught SyntaxError: Unexpected token {

```
At file:///usr/share/atom/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2Fsrv%2Fsites%2Fbricade-riem%22%2C%22initialLine%22%3Anull%2C%22initialColumn%22%3Anull%7D%5D%2C%22bootstrapScript%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fusr%2Fshare%2Fatom%2Fresources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%221.0.19%22%2C%22initialPaths%22%3A%5B%22%2Fsrv%2Fsites%2Fbricade-riem%22%5D%7D:2

SyntaxError: Unexpected token {
  at Object.parse (native)
  at [object Object].module.exports._deserialize (/home/jorik/.atom/packages/autocomplete-python/lib/provider.coffee:122:21)
  at provider.BufferedProcess.stdout (/home/jorik/.atom/packages/autocomplete-python/lib/provider.coffee:50:10)
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:85:13)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at Pipe.onread (net.js:520:20)

```

### Commands

```
     -3:29.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:48.8.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -1:48.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:37.8.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:33 core:backspace (atom-text-editor.editor.is-focused)
     -0:14.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:14.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:12.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:12.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:11.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.1.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:07.3.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
  9x -0:06.9.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:05.8.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:05.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:01.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-visual-studio-code-ui",
      "material-design-syntax"
    ],
    "openEmptyEditorOnStart": false,
    "autoHideMenuBar": true
  },
  "autocomplete-python": {}
}
```

### Installed Packages

```coffee
# User
atom-visual-studio-code-ui, v1.3.2
autocomplete-python, v0.9.0
autohide-tree-view, v0.25.1
autoupdate-packages, v1.1.2
color-picker, v2.0.13
django-atom, v0.2.4
git-projects, v1.15.0
highlight-line, v0.11.0
highlight-selected, v0.10.1
linter, v1.9.1
linter-pep8, v1.0.1
linter-pylint, v1.0.3
material-design-syntax, v1.7.0
minimap, v4.15.0
minimap-find-and-replace, v4.3.1
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
pigments, v0.18.0
python-tools, v0.6.5
set-syntax, v0.3.0
soft-wrap-indicator, v0.7.0
terminal-plus, v0.12.2
tool-bar, v0.1.9
tool-bar-besser, v0.2.4
unfancy-file-icons, v0.2.0

# Dev
No dev packages
```

**Comment by JostCrow** [comment]
Duplicate of #95
