### ISSUE TITLE
Failed to load the autocomplete-python package

### ISSUE THREAD

**Issue by yuxianggu** [sadovnychyi/autocomplete-python#98]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Home
**Thrown From**: [autocomplete-python](https://github.com/sadovnychyi/autocomplete-python) package, v0.9.0

### Stack Trace

Failed to load the autocomplete-python package

```
At Error parsing C:\Users\Yuxiang\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\package.json: Unexpected end of input

SyntaxError: Error parsing C:\Users\Yuxiang\.atom\packages\autocomplete-python\node_modules\atom-space-pen-views\package.json: Unexpected end of input
    at Object.parse (native)
    at readPackage (module.js:77:52)
    at tryPackage (module.js:87:13)
    at Function.Module._findPath (module.js:155:20)
    at Module._resolveFilename (module.js:332:25)
    at Function.Module._resolveFilename (C:\Users\Yuxiang\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Yuxiang\.atom\packages\autocomplete-python\lib\definitions-view.coffee:1:24)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-python, v0.9.0
color-picker, v2.0.13
file-icons, v1.6.11
jsformat, v0.9.0
language-r, v0.4.0
language-vb, v0.1.0-pre1
language-vbscript, v0.6.1
linter, v1.9.1
minimap, v4.15.0
minimap-color-highlight, v4.1.4
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
script, vundefined
Sublime-Style-Column-Selection, v1.3.0

# Dev
No dev packages
```

**Comment by sadovnychyi** [comment]
It seems like you got incomplete dependency due to apm bug. Can you try to
remove & install the package again?

**Comment by Arengorn** [comment]
Had the same issue here, reinstalled and it started working again.
